"""cloudinary_updation

Revision ID: 5e62d3f524f9
Revises: 289d9b88a3b1
Create Date: 2026-07-20 04:10:23.700483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e62d3f524f9'
down_revision: Union[str, Sequence[str], None] = '289d9b88a3b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category_image_url', sa.String(length=500), nullable=False))
    op.add_column('categories', sa.Column('category_public_id', sa.String(length=255), nullable=False))
    op.drop_column('categories', 'category_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category_image', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('categories', 'category_public_id')
    op.drop_column('categories', 'category_image_url')
    # ### end Alembic commands ###
